export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const AUTHENTICATE_LOGIN_SUCCESS = 'AUTHENTICATE_LOGIN_SUCCESS';
export const AUTHENTICATE_LOGIN_FAILED = 'AUTHENTICATE_LOGIN_FAILED';
export const AUTHENTICATE_LOGOUT_SUCCESS = 'AUTHENTICATE_LOGOUT_SUCCESS';
export const CLEAR_AUTH_MESSAGE = 'CLEAR_AUTH_MESSAGE';

export const GET_USER_DETAILS_SUCCESS = 'GET_USER_DETAILS_SUCCESS';
export const LOAD_USER_DETAILS_SUCCESS = 'LOAD_USER_DETAILS_SUCCESS';
export const CLEAR_USER_DETAILS = 'CLEAR_USER_DETAILS';

export const CREATE_USER_ACCOUNT_SUCCESS = 'CREATE_USER_ACCOUNT_SUCCESS';
export const CREATE_USER_ACCOUNT_FAILED = 'CREATE_USER_ACCOUNT_FAILED';
export const CREATE_USER_ACCOUNT_MESSAGE = 'CREATE_USER_ACCOUNT_MESSAGE';
export const CREATE_USER_ACCOUNT_CLEAR_MESSAGE = 'CREATE_USER_ACCOUNT_CLEAR_MESSAGE';

export const GET_ACCOUNT_LIST_SUCCESS = 'GET_ACCOUNT_LIST_SUCCESS';
export const GET_ACCOUNT_LIST_FAILED = 'GET_ACCOUNT_LIST_FAILED';
export const CLEAR_ACCOUNT_LIST = 'CLEAR_ACCOUNT_LIST';

export const GET_PATIENT_LIST_SUCCESS = 'GET_PATIENT_LIST_SUCCESS';
export const GET_PATIENT_LIST_FAILED = 'GET_PATIENT_LIST_FAILED';
export const CLEAR_PATIENT_LIST = 'CLEAR_PATIENT_LIST';
